DROP TRIGGER IF EXISTS pursuit_portfolio_execution_proposal_decisions_reject_truncate ON pursuit_portfolio_execution_proposal_decisions;
DROP TRIGGER IF EXISTS pursuit_portfolio_execution_proposal_decisions_reject_delete ON pursuit_portfolio_execution_proposal_decisions;
DROP TRIGGER IF EXISTS pursuit_portfolio_execution_proposal_decisions_reject_update ON pursuit_portfolio_execution_proposal_decisions;
DROP FUNCTION IF EXISTS reject_pursuit_portfolio_execution_proposal_decision_mutation();
DROP TRIGGER IF EXISTS pursuit_portfolio_execution_proposal_decisions_validate_insert ON pursuit_portfolio_execution_proposal_decisions;
DROP FUNCTION IF EXISTS validate_pursuit_portfolio_execution_proposal_decision_insert();
DROP TABLE IF EXISTS pursuit_portfolio_execution_proposal_decisions;
