#!/usr/bin/env bash
#
# Generate real secrets for a local HAI stack.
#
# The values shipped in .env.example ("change-this-...") are placeholders. With
# RUN_MODE=production the backend reports /readyz as not_ready while any of them
# is still in place, so this script exists to make doing the right thing a
# one-liner:
#
#   ./scripts/generate-secrets.sh >> .env.local
#
# Then remove the older duplicate keys, or regenerate .env.local from scratch:
#
#   cp .env.example .env.local
#   ./scripts/generate-secrets.sh >> .env.local
#
# Later assignments win in docker compose's env-file parsing, so appending is
# enough to override the placeholders above them.

set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets" >&2
  exit 1
fi

secret() { openssl rand -hex 32; }

cat <<EOF

# --- Generated secrets ($(date -u +%Y-%m-%dT%H:%M:%SZ)) ---
# Generated by scripts/generate-secrets.sh. Do not commit this file.
BACKEND_API_SHARED_KEY=$(secret)
HAI_MEMORY_ENCRYPTION_KEY=$(secret)
JWT_SECRET=$(secret)
HAI_APPROVAL_PROOF_SIGNING_KEY=$(secret)
EOF
